version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3
    steps:
      - checkout
      - restore_cache:
          keys:
            - rubygems-v1-{{ checksum "Gemfile.lock" }}
            - rubygems-v1-fallback
      - run:
          name: Update APT
          command: sudo apt-get update
      - run:
          name: Configure Bundler setp 1
          command: echo 'export BUNDLER_VERSION=2.0.2' >> $BASH_ENV
      - run:
          name: Configure Bundler setp 3  
          command: source $BASH_ENV
      - run:
          name: Configure Bundler setp 3
          command: gem install bundler
      - run:
          name: Fix JS Runtime
          command: gem install therubyracer
      - run:
          name: Fix JS Runtime 2
          command: gem install execjs
      - run:
          name: Fix JS Runtime 3
          command: gem install jekyll
      - run:
          name: Fix JS Runtime 4
          command: sudo apt-get install nodejs
      - run:
          name: Install Rack
          command: gem install rack
      - run:
          name: Install Capybara
          command: gem install capybara
      - run:
          name: Update Capybara
          command: bundle update capybara
      - run:
          name: Install github-pages
          command: gem install github-pages
      - run:
          name: Update github-pages
          command: bundle update github-pages
      - run:
          name: Bundle Install
          command: bundle check || bundle install
      - save_cache:
          key: rubygems-v1-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: Jekyll build
          command: bundle exec jekyll build
      - run:
          name: HTMLProofer tests
          command: |
            bundle exec htmlproofer ./_site \
              --allow-hash-href \
              --check-favicon  \
              --check-html \
              --disable-external
      - persist_to_workspace:
          root: ./
          paths:
            - _site
