version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.2
    steps:
      - checkout
      - restore_cache:
          keys:
            - rubygems-v1-{{ checksum "Gemfile.lock" }}
            - rubygems-v1-fallback
      - run:
          name: Update APT
          command: sudo apt-get update
      - run:
          name: Install bundler
          command: gem install bundler
      - run:
          name: Install jekyll Gem
          command: gem install jekyll
      - run:
          name: Bundle Install
          command: bundle install
      - save_cache:
          key: rubygems-v1-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: Jekyll build
          command: bundle exec jekyll build
      - run:
          name: HTMLProofer tests
          command: |
            bundle exec htmlproofer ./_site \
              --allow-hash-href \
              --check-favicon  \
              --check-html \
              --disable-external
      - persist_to_workspace:
          root: ./
          paths:
            - _site
