name: Automerge Pull Requests
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
jobs:
  automerge:
    name: Automerge Dependency Updates
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]' || contains(github.event.pull_request.labels.*.name, 'dependencies')
    steps:
      - name: 'Wait for status checks'
        id: waitforstatuschecks
        uses: "WyriHaximus/github-action-wait-for-status@v1.8.0"
        with:
          ignoreActions: Automerge Dependabot,Code coverage
          checkInterval: 13
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - name: Auto approve
        uses: hmarr/auto-approve-action@v4.0.0
        if: steps.waitforstatuschecks.outputs.status == 'success'
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Merge pull requests
        uses: pascalgn/automerge-action@v0.16.2
        if: steps.waitforstatuschecks.outputs.status == 'success'
        env:
          MERGE_METHOD: "merge"
          MERGE_LABELS: ""
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
