name: Auto merge dependabot PRs

on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status:

permissions:
  contents: read
  pull-requests: write
  checks: read

concurrency:
  group: "automerge-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@v0.16.4"
        env:
          MERGE_LABELS: ""
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - name: Automerge summary
        if: always()
        run: |
          echo "## Automerge summary" >> $GITHUB_STEP_SUMMARY || true
          echo "- Actor: ${{ github.actor }}" >> $GITHUB_STEP_SUMMARY || true
          echo "- Event: ${{ github.event_name }}" >> $GITHUB_STEP_SUMMARY || true
          echo "- Run conclusion: ${{ job.status }}" >> $GITHUB_STEP_SUMMARY || true
          if [ -n "${{ github.event.pull_request.html_url || github.event.pull_request.url }}" ]; then
            echo "- PR: ${{ github.event.pull_request.html_url || github.event.pull_request.url }}" >> $GITHUB_STEP_SUMMARY || true
          fi
