name: Deploy Pages

on:
  workflow_dispatch:
    inputs:
      variant:
        description: Export variant to deploy (about | blog | single-contact | single-newsletter | single-socials)
        required: false
        type: string
        default: about

jobs:
  call-reusable:
    uses: lbenicio/aboutme-v2/.github/workflows/export-and-deploy.yml@main
    with:
      variant: ${{ inputs.variant }}
