name: Telegram notification
on:
  workflow_run:
    workflows:
      - Deploy Hugo site to Pages
      - Publish docker image on Github Container Registry
      - Release new version
      - Auto merge dependabot PRs
    branches:
      - main
    types: 
      - completed
  workflow_dispatch:
jobs:
  notification:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Send Telegram message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.ChatID }}
          token: ${{ secrets.BotToken }}
          format: markdown
          message: |
            Code Deployed: ${{ github.repository }}

            ${{ github.actor }} created commit:
            ${{ github.event.workflow_run.head_commit.message }}

            [View action run](${{ github.event.workflow_run.html_url }})
            [Cancel action run](${{ github.event.workflow_run.cancel_url }})

            Workflow: ${{ github.event.workflow_run.name }}
            Job status: ${{ github.event.workflow_run.conclusion == 'success' && '✅' || '🚫' }} ${{ github.event.workflow_run.conclusion }}
            
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}