name: Publish docker image on Github Container Registry
on:
  workflow_run:
    workflows:
      - Deploy Hugo site to Pages
    branches:
      - main
    types: 
      - completed
  workflow_dispatch:
jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the docker image
        run: docker build . --tag ghcr.io/lbenicio/v2-home:latest --tag ghcr.io/lbenicio/v2-home:${{ github.sha }}
      - name: Publish the docker image
        run: docker push ghcr.io/lbenicio/v2-home --all-tags