name: Release

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Default workflow-level permissions (least privilege)
permissions:
  contents: read
  packages: write
  issues: write

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency:
      group: "release-${{ github.ref }}"
      cancel-in-progress: false
    # Job-level permissions: releases need write access to contents (tags/releases)
    permissions:
      contents: write
      packages: write
      issues: write
    steps:
      - uses: actions/checkout@v5
      - id: release
        uses: CupOfTea696/gh-action-auto-release@v1.0.2
        with:
          title: "Release: v$version"
          tag: "v$semver"
          draft: false
          regex: "/^release: v#{semver}$/i"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Release summary
        if: always()
        run: |
          echo "## Release summary" >> $GITHUB_STEP_SUMMARY || true
          echo "- Release tag: v$semver" >> $GITHUB_STEP_SUMMARY || true
          echo "- Release title: Release: v$version" >> $GITHUB_STEP_SUMMARY || true
          # If the gh-action-auto-release exposes a release URL, include it
          if [ -n "${{ steps.release.outputs.html_url }}" ]; then
            echo "- Release URL: ${{ steps.release.outputs.html_url }}" >> $GITHUB_STEP_SUMMARY || true
          fi